import styles from './style.module.css'
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About Page",
  description: "Generated by ayub",
};
export default function  AboutLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <nav>

    About Navbar
    </nav>
    <main className={styles.main}>
        {children}  
    </main></>
    
  )
}
